# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spinloop < Formula
  desc "Configure opencode provider catalogues"
  homepage "https://github.com/spinloop-ai/spinloop"
  version "1.29.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spinloop-ai/spinloop/releases/download/v1.29.0/spinloop_darwin_amd64.tar.gz"
      sha256 "673db694c7d1b9939358164e4ef5deee412b87d2000b0ee17648442d8a4ed2a5"

      define_method(:install) do
        bin.install "spinloop"
        generate_completions_from_executable(bin/"spinloop", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spinloop-ai/spinloop/releases/download/v1.29.0/spinloop_darwin_arm64.tar.gz"
      sha256 "c31f36cd15c752434bd26bf1fa2725422697d0fec715c5c344d9e3e5922e88ea"

      define_method(:install) do
        bin.install "spinloop"
        generate_completions_from_executable(bin/"spinloop", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/spinloop-ai/spinloop/releases/download/v1.29.0/spinloop_linux_amd64.tar.gz"
      sha256 "b68841bd224d256bde32f5a8543b45c0c48b0484eda855b96e86216d5ef16e35"
      define_method(:install) do
        bin.install "spinloop"
        generate_completions_from_executable(bin/"spinloop", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spinloop-ai/spinloop/releases/download/v1.29.0/spinloop_linux_arm64.tar.gz"
      sha256 "ac3b129a3c0ddf1503d1ec3bc608667b72a941959b9cd0fdfa4f30b2f6481c99"
      define_method(:install) do
        bin.install "spinloop"
        generate_completions_from_executable(bin/"spinloop", "completion", shells: [:bash, :zsh])
      end
    end
  end

  test do
    system "#{bin}/spinloop", "--help"
  end
end
