# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spinloop < Formula
  desc "Configure opencode provider catalogues"
  homepage "https://github.com/spinloop-ai/spinloop"
  version "1.37.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spinloop-ai/spinloop/releases/download/v1.37.0/spinloop_darwin_amd64.tar.gz"
      sha256 "6be9921c82463c4e065e3f0696b36ee55247407a2722bd4d1504bb9868fda21f"

      define_method(:install) do
        bin.install "spinloop"
        generate_completions_from_executable(bin/"spinloop", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spinloop-ai/spinloop/releases/download/v1.37.0/spinloop_darwin_arm64.tar.gz"
      sha256 "b2c85a5438268069a5f969352cf3cc393207c81e99bada0279af651a745a8ec2"

      define_method(:install) do
        bin.install "spinloop"
        generate_completions_from_executable(bin/"spinloop", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/spinloop-ai/spinloop/releases/download/v1.37.0/spinloop_linux_amd64.tar.gz"
      sha256 "3f809cfbe99989068563d7f14192ed9e4a21d6080ab25b99659bd9f87a80828c"
      define_method(:install) do
        bin.install "spinloop"
        generate_completions_from_executable(bin/"spinloop", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spinloop-ai/spinloop/releases/download/v1.37.0/spinloop_linux_arm64.tar.gz"
      sha256 "b8b668fed790f779907c4e192b0b795ce556a8a15c1cdefb6bf8b2d56a1fa106"
      define_method(:install) do
        bin.install "spinloop"
        generate_completions_from_executable(bin/"spinloop", "completion", shells: [:bash, :zsh])
      end
    end
  end

  test do
    system "#{bin}/spinloop", "--help"
  end
end
