# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spinloop < Formula
  desc "Configure opencode provider catalogues"
  homepage "https://github.com/spinloop-ai/spinloop"
  version "1.43.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spinloop-ai/spinloop/releases/download/v1.43.0/spinloop_darwin_amd64.tar.gz"
      sha256 "266a90b3b18d846b058ba65d6e901215c9588d63df767db0e411700bedcf4c6f"

      define_method(:install) do
        bin.install "spinloop"
        generate_completions_from_executable(bin/"spinloop", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spinloop-ai/spinloop/releases/download/v1.43.0/spinloop_darwin_arm64.tar.gz"
      sha256 "21fa23bfc0c01eefe21d33f39163bcc203cc98ddf8ba1de0dcb3c54737d322ee"

      define_method(:install) do
        bin.install "spinloop"
        generate_completions_from_executable(bin/"spinloop", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/spinloop-ai/spinloop/releases/download/v1.43.0/spinloop_linux_amd64.tar.gz"
      sha256 "2ac68185e809a97ff8e7a51517c671f4bb55ef0b0545478ef6d903037a0512a4"
      define_method(:install) do
        bin.install "spinloop"
        generate_completions_from_executable(bin/"spinloop", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spinloop-ai/spinloop/releases/download/v1.43.0/spinloop_linux_arm64.tar.gz"
      sha256 "ec8c3168e558a7064ff9cdcff46a4a98ebb45c1f0619233893fd12babb6cf316"
      define_method(:install) do
        bin.install "spinloop"
        generate_completions_from_executable(bin/"spinloop", "completion", shells: [:bash, :zsh])
      end
    end
  end

  test do
    system "#{bin}/spinloop", "--help"
  end
end
